version: '3.1'

services:

  vellMed-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: "vollmed"
      MYSQL_DATABASE: "vollMed"
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - '3308:3306'
