spring:
  datasource:
    url: jdbc:mysql://localhost:3308/vollMed?allowPublicKeyRetrieval=true&useSSL=false
    username: vollmed
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
